<?php 
class Student {
    private $list = [
        [
        'student_id'    => 'STU001',
        'first_name'    => 'Jessica',
        'last_name'     => 'Garcia',
        'date_of_birth' => '2005-03-15',
        'gender'        => 2,
        'class'         => 'BA102',
        'major'         => 'Electrical Engineering',
        'email'         => 'jessica.garcia001@student.edu',
        'phone_number'  => '555-9265142',
        'address'       => 'Los Angeles',
        'gpa'           => 2.2,
    ],
    [
        'student_id'    => 'STU002',
        'first_name'    => 'Susan',
        'last_name'     => 'Smith',
        'date_of_birth' => '2005-04-22',
        'gender'        => 2,
        'class'         => 'BA101',
        'major'         => 'Electrical Engineering',
        'email'         => 'susan.smith002@student.edu',
        'phone_number'  => '555-8384627',
        'address'       => 'Austin',
        'gpa'           => 2.87,
    ],
    [
        'student_id'    => 'STU003',
        'first_name'    => 'Karen',
        'last_name'     => 'Jones',
        'date_of_birth' => '2003-07-26',
        'gender'        => 1,
        'class'         => 'BA101',
        'major'         => 'Accounting',
        'email'         => 'karen.jones003@student.edu',
        'phone_number'  => '555-6793765',
        'address'       => 'Chicago',
        'gpa'           => 3.52,
    ],
    [
        'student_id'    => 'STU004',
        'first_name'    => 'John',
        'last_name'     => 'Brown',
        'date_of_birth' => '2002-01-12',
        'gender'        => 3,
        'class'         => 'BA101',
        'major'         => 'Computer Science',
        'email'         => 'john.brown004@student.edu',
        'phone_number'  => '555-1960951',
        'address'       => 'New York',
        'gpa'           => 3.29,
    ],
    [
        'student_id'    => 'STU005',
        'first_name'    => 'Matthew',
        'last_name'     => 'Garcia',
        'date_of_birth' => '2003-04-06',
        'gender'        => 2,
        'class'         => 'BA102',
        'major'         => 'English Literature',
        'email'         => 'matthew.garcia005@student.edu',
        'phone_number'  => '555-5535755',
        'address'       => 'Houston',
        'gpa'           => 2.95,
    ],
    [
        'student_id'    => 'STU006',
        'first_name'    => 'Patricia',
        'last_name'     => 'Martin',
        'date_of_birth' => '2006-10-06',
        'gender'        => 3,
        'class'         => 'EN101',
        'major'         => 'Civil Engineering',
        'email'         => 'patricia.martin006@student.edu',
        'phone_number'  => '555-9912633',
        'address'       => 'Austin',
        'gpa'           => 2.86,
    ],
    [
        'student_id'    => 'STU007',
        'first_name'    => 'Mary',
        'last_name'     => 'Lopez',
        'date_of_birth' => '2003-03-15',
        'gender'        => 2,
        'class'         => 'BA101',
        'major'         => 'Civil Engineering',
        'email'         => 'mary.lopez007@student.edu',
        'phone_number'  => '555-9382778',
        'address'       => 'Chicago',
        'gpa'           => 3.71,
    ],
    [
        'student_id'    => 'STU008',
        'first_name'    => 'Robert',
        'last_name'     => 'Johnson',
        'date_of_birth' => '2006-05-01',
        'gender'        => 2,
        'class'         => 'BA101',
        'major'         => 'English Literature',
        'email'         => 'robert.johnson008@student.edu',
        'phone_number'  => '555-2082828',
        'address'       => 'Dallas',
        'gpa'           => 3.71,
    ],
    [
        'student_id'    => 'STU009',
        'first_name'    => 'Elizabeth',
        'last_name'     => 'Martinez',
        'date_of_birth' => '2002-01-09',
        'gender'        => 2,
        'class'         => 'CS102',
        'major'         => 'Accounting',
        'email'         => 'elizabeth.martinez009@student.edu',
        'phone_number'  => '555-2933312',
        'address'       => 'New York',
        'gpa'           => 3.02,
    ],
    [
        'student_id'    => 'STU010',
        'first_name'    => 'Barbara',
        'last_name'     => 'Smith',
        'date_of_birth' => '2005-11-28',
        'gender'        => 2,
        'class'         => 'BA101',
        'major'         => 'Accounting',
        'email'         => 'barbara.smith010@student.edu',
        'phone_number'  => '555-6226653',
        'address'       => 'Austin',
        'gpa'           => 2.79,
    ],
    [
        'student_id'    => 'STU011',
        'first_name'    => 'Patricia',
        'last_name'     => 'Williams',
        'date_of_birth' => '2003-05-01',
        'gender'        => 1,
        'class'         => 'ME101',
        'major'         => 'Electrical Engineering',
        'email'         => 'patricia.williams011@student.edu',
        'phone_number'  => '555-4063562',
        'address'       => 'New York',
        'gpa'           => 2.43,
    ],
    [
        'student_id'    => 'STU012',
        'first_name'    => 'Mark',
        'last_name'     => 'Anderson',
        'date_of_birth' => '2003-07-08',
        'gender'        => 1,
        'class'         => 'EN101',
        'major'         => 'Civil Engineering',
        'email'         => 'mark.anderson012@student.edu',
        'phone_number'  => '555-5486771',
        'address'       => 'New York',
        'gpa'           => 2.54,
    ],
    [
        'student_id'    => 'STU013',
        'first_name'    => 'Elizabeth',
        'last_name'     => 'Rodriguez',
        'date_of_birth' => '2005-12-01',
        'gender'        => 3,
        'class'         => 'CS101',
        'major'         => 'English Literature',
        'email'         => 'elizabeth.rodriguez013@student.edu',
        'phone_number'  => '555-8633651',
        'address'       => 'Chicago',
        'gpa'           => 3.29,
    ],
    [
        'student_id'    => 'STU014',
        'first_name'    => 'Thomas',
        'last_name'     => 'Moore',
        'date_of_birth' => '2002-09-26',
        'gender'        => 1,
        'class'         => 'BA102',
        'major'         => 'Business Administration',
        'email'         => 'thomas.moore014@student.edu',
        'phone_number'  => '555-7678840',
        'address'       => 'Phoenix',
        'gpa'           => 3.45,
    ],
    [
        'student_id'    => 'STU015',
        'first_name'    => 'Patricia',
        'last_name'     => 'Anderson',
        'date_of_birth' => '2004-08-14',
        'gender'        => 1,
        'class'         => 'EN101',
        'major'         => 'Business Administration',
        'email'         => 'patricia.anderson015@student.edu',
        'phone_number'  => '555-8514192',
        'address'       => 'New York',
        'gpa'           => 3.77,
    ],
    [
        'student_id'    => 'STU016',
        'first_name'    => 'Daniel',
        'last_name'     => 'Garcia',
        'date_of_birth' => '2003-03-21',
        'gender'        => 3,
        'class'         => 'EN101',
        'major'         => 'Mechanical Engineering',
        'email'         => 'daniel.garcia016@student.edu',
        'phone_number'  => '555-2237357',
        'address'       => 'Houston',
        'gpa'           => 2.18,
    ],
    [
        'student_id'    => 'STU017',
        'first_name'    => 'Robert',
        'last_name'     => 'Anderson',
        'date_of_birth' => '2005-11-18',
        'gender'        => 2,
        'class'         => 'CE101',
        'major'         => 'English Literature',
        'email'         => 'robert.anderson017@student.edu',
        'phone_number'  => '555-2930966',
        'address'       => 'Austin',
        'gpa'           => 2.14,
    ],
    [
        'student_id'    => 'STU018',
        'first_name'    => 'Charles',
        'last_name'     => 'Taylor',
        'date_of_birth' => '2004-10-06',
        'gender'        => 2,
        'class'         => 'CS101',
        'major'         => 'Business Administration',
        'email'         => 'charles.taylor018@student.edu',
        'phone_number'  => '555-5806499',
        'address'       => 'Austin',
        'gpa'           => 2.55,
    ],
    [
        'student_id'    => 'STU019',
        'first_name'    => 'Anthony',
        'last_name'     => 'Hernandez',
        'date_of_birth' => '2003-08-27',
        'gender'        => 2,
        'class'         => 'ME101',
        'major'         => 'English Literature',
        'email'         => 'anthony.hernandez019@student.edu',
        'phone_number'  => '555-7895217',
        'address'       => 'Phoenix',
        'gpa'           => 2.51,
    ],
    [
        'student_id'    => 'STU020',
        'first_name'    => 'Richard',
        'last_name'     => 'Rodriguez',
        'date_of_birth' => '2006-08-18',
        'gender'        => 1,
        'class'         => 'CS102',
        'major'         => 'Accounting',
        'email'         => 'richard.rodriguez020@student.edu',
        'phone_number'  => '555-9211178',
        'address'       => 'Austin',
        'gpa'           => 3.89,
    ],
    [
        'student_id'    => 'STU021',
        'first_name'    => 'Robert',
        'last_name'     => 'Martin',
        'date_of_birth' => '2006-05-15',
        'gender'        => 2,
        'class'         => 'CS101',
        'major'         => 'Mechanical Engineering',
        'email'         => 'robert.martin021@student.edu',
        'phone_number'  => '555-3438488',
        'address'       => 'Houston',
        'gpa'           => 3.63,
    ],
    [
        'student_id'    => 'STU022',
        'first_name'    => 'Susan',
        'last_name'     => 'Rodriguez',
        'date_of_birth' => '2003-07-08',
        'gender'        => 1,
        'class'         => 'CE101',
        'major'         => 'Computer Science',
        'email'         => 'susan.rodriguez022@student.edu',
        'phone_number'  => '555-5235784',
        'address'       => 'Los Angeles',
        'gpa'           => 2.37,
    ],
    [
        'student_id'    => 'STU023',
        'first_name'    => 'David',
        'last_name'     => 'Gonzalez',
        'date_of_birth' => '2005-08-03',
        'gender'        => 1,
        'class'         => 'BA101',
        'major'         => 'Electrical Engineering',
        'email'         => 'david.gonzalez023@student.edu',
        'phone_number'  => '555-5277689',
        'address'       => 'Chicago',
        'gpa'           => 3.82,
    ],
    [
        'student_id'    => 'STU024',
        'first_name'    => 'David',
        'last_name'     => 'Garcia',
        'date_of_birth' => '2002-02-17',
        'gender'        => 3,
        'class'         => 'CS102',
        'major'         => 'Marketing',
        'email'         => 'david.garcia024@student.edu',
        'phone_number'  => '555-3707428',
        'address'       => 'Dallas',
        'gpa'           => 2.18,
    ],
    [
        'student_id'    => 'STU025',
        'first_name'    => 'Susan',
        'last_name'     => 'Garcia',
        'date_of_birth' => '2005-06-01',
        'gender'        => 1,
        'class'         => 'CE101',
        'major'         => 'Business Administration',
        'email'         => 'susan.garcia025@student.edu',
        'phone_number'  => '555-4385167',
        'address'       => 'Chicago',
        'gpa'           => 2.52,
    ],
    [
        'student_id'    => 'STU026',
        'first_name'    => 'Barbara',
        'last_name'     => 'Anderson',
        'date_of_birth' => '2006-11-08',
        'gender'        => 2,
        'class'         => 'BA102',
        'major'         => 'English Literature',
        'email'         => 'barbara.anderson026@student.edu',
        'phone_number'  => '555-5048278',
        'address'       => 'San Diego',
        'gpa'           => 3.68,
    ],
    [
        'student_id'    => 'STU027',
        'first_name'    => 'Matthew',
        'last_name'     => 'Martinez',
        'date_of_birth' => '2003-05-09',
        'gender'        => 1,
        'class'         => 'EE101',
        'major'         => 'Electrical Engineering',
        'email'         => 'matthew.martinez027@student.edu',
        'phone_number'  => '555-4599528',
        'address'       => 'Phoenix',
        'gpa'           => 3.94,
    ],
    [
        'student_id'    => 'STU028',
        'first_name'    => 'James',
        'last_name'     => 'Gonzalez',
        'date_of_birth' => '2003-02-08',
        'gender'        => 2,
        'class'         => 'BA102',
        'major'         => 'Computer Science',
        'email'         => 'james.gonzalez028@student.edu',
        'phone_number'  => '555-6950769',
        'address'       => 'San Diego',
        'gpa'           => 3.32,
    ],
    [
        'student_id'    => 'STU029',
        'first_name'    => 'Michael',
        'last_name'     => 'Jones',
        'date_of_birth' => '2003-02-24',
        'gender'        => 2,
        'class'         => 'EE101',
        'major'         => 'Mechanical Engineering',
        'email'         => 'michael.jones029@student.edu',
        'phone_number'  => '555-9256902',
        'address'       => 'Phoenix',
        'gpa'           => 3.46,
    ],
    [
        'student_id'    => 'STU030',
        'first_name'    => 'Charles',
        'last_name'     => 'Martinez',
        'date_of_birth' => '2006-08-02',
        'gender'        => 1,
        'class'         => 'BA102',
        'major'         => 'Mechanical Engineering',
        'email'         => 'charles.martinez030@student.edu',
        'phone_number'  => '555-3233832',
        'address'       => 'Los Angeles',
        'gpa'           => 3.6,
    ],
    [
        'student_id'    => 'STU031',
        'first_name'    => 'Sandra',
        'last_name'     => 'Taylor',
        'date_of_birth' => '2004-02-28',
        'gender'        => 2,
        'class'         => 'ME101',
        'major'         => 'Computer Science',
        'email'         => 'sandra.taylor031@student.edu',
        'phone_number'  => '555-9131742',
        'address'       => 'Houston',
        'gpa'           => 2.46,
    ],
    [
        'student_id'    => 'STU032',
        'first_name'    => 'Richard',
        'last_name'     => 'Hernandez',
        'date_of_birth' => '2005-03-15',
        'gender'        => 2,
        'class'         => 'CE101',
        'major'         => 'Mechanical Engineering',
        'email'         => 'richard.hernandez032@student.edu',
        'phone_number'  => '555-3872738',
        'address'       => 'Phoenix',
        'gpa'           => 3.62,
    ],
    [
        'student_id'    => 'STU033',
        'first_name'    => 'Sarah',
        'last_name'     => 'Jackson',
        'date_of_birth' => '2003-12-28',
        'gender'        => 1,
        'class'         => 'CE101',
        'major'         => 'Marketing',
        'email'         => 'sarah.jackson033@student.edu',
        'phone_number'  => '555-1966189',
        'address'       => 'Chicago',
        'gpa'           => 2.03,
    ],
    [
        'student_id'    => 'STU034',
        'first_name'    => 'Elizabeth',
        'last_name'     => 'Jackson',
        'date_of_birth' => '2004-11-20',
        'gender'        => 1,
        'class'         => 'BA101',
        'major'         => 'English Literature',
        'email'         => 'elizabeth.jackson034@student.edu',
        'phone_number'  => '555-5818392',
        'address'       => 'Phoenix',
        'gpa'           => 3.13,
    ],
    [
        'student_id'    => 'STU035',
        'first_name'    => 'Lisa',
        'last_name'     => 'Moore',
        'date_of_birth' => '2006-09-18',
        'gender'        => 1,
        'class'         => 'BA101',
        'major'         => 'Accounting',
        'email'         => 'lisa.moore035@student.edu',
        'phone_number'  => '555-7851569',
        'address'       => 'Los Angeles',
        'gpa'           => 3.56,
    ],
    [
        'student_id'    => 'STU036',
        'first_name'    => 'Robert',
        'last_name'     => 'Miller',
        'date_of_birth' => '2003-05-09',
        'gender'        => 1,
        'class'         => 'BA101',
        'major'         => 'Accounting',
        'email'         => 'robert.miller036@student.edu',
        'phone_number'  => '555-7186541',
        'address'       => 'New York',
        'gpa'           => 3.38,
    ],
    [
        'student_id'    => 'STU037',
        'first_name'    => 'James',
        'last_name'     => 'Jackson',
        'date_of_birth' => '2002-01-25',
        'gender'        => 2,
        'class'         => 'EN101',
        'major'         => 'Accounting',
        'email'         => 'james.jackson037@student.edu',
        'phone_number'  => '555-1901705',
        'address'       => 'Chicago',
        'gpa'           => 3.3,
    ],
    [
        'student_id'    => 'STU038',
        'first_name'    => 'Barbara',
        'last_name'     => 'Jackson',
        'date_of_birth' => '2006-05-01',
        'gender'        => 3,
        'class'         => 'CE101',
        'major'         => 'Marketing',
        'email'         => 'barbara.jackson038@student.edu',
        'phone_number'  => '555-9907661',
        'address'       => 'Los Angeles',
        'gpa'           => 2.96,
    ],
    [
        'student_id'    => 'STU039',
        'first_name'    => 'Paul',
        'last_name'     => 'Davis',
        'date_of_birth' => '2006-01-05',
        'gender'        => 1,
        'class'         => 'BA101',
        'major'         => 'Accounting',
        'email'         => 'paul.davis039@student.edu',
        'phone_number'  => '555-1697965',
        'address'       => 'San Diego',
        'gpa'           => 2.9,
    ],
    [
        'student_id'    => 'STU040',
        'first_name'    => 'Charles',
        'last_name'     => 'Rodriguez',
        'date_of_birth' => '2004-09-26',
        'gender'        => 1,
        'class'         => 'CS101',
        'major'         => 'Civil Engineering',
        'email'         => 'charles.rodriguez040@student.edu',
        'phone_number'  => '555-5368563',
        'address'       => 'San Diego',
        'gpa'           => 3.43,
    ],
    [
        'student_id'    => 'STU041',
        'first_name'    => 'Jennifer',
        'last_name'     => 'Williams',
        'date_of_birth' => '2006-08-20',
        'gender'        => 2,
        'class'         => 'EE101',
        'major'         => 'Marketing',
        'email'         => 'jennifer.williams041@student.edu',
        'phone_number'  => '555-4987581',
        'address'       => 'Chicago',
        'gpa'           => 2.75,
    ],
    [
        'student_id'    => 'STU042',
        'first_name'    => 'Mary',
        'last_name'     => 'Davis',
        'date_of_birth' => '2005-09-18',
        'gender'        => 3,
        'class'         => 'EE101',
        'major'         => 'Computer Science',
        'email'         => 'mary.davis042@student.edu',
        'phone_number'  => '555-7050349',
        'address'       => 'San Diego',
        'gpa'           => 3.73,
    ],
    [
        'student_id'    => 'STU043',
        'first_name'    => 'Charles',
        'last_name'     => 'Williams',
        'date_of_birth' => '2002-11-28',
        'gender'        => 1,
        'class'         => 'BA102',
        'major'         => 'Computer Science',
        'email'         => 'charles.williams043@student.edu',
        'phone_number'  => '555-5944240',
        'address'       => 'Houston',
        'gpa'           => 3.07,
    ],
    [
        'student_id'    => 'STU044',
        'first_name'    => 'Lisa',
        'last_name'     => 'Hernandez',
        'date_of_birth' => '2002-11-01',
        'gender'        => 2,
        'class'         => 'EE101',
        'major'         => 'Civil Engineering',
        'email'         => 'lisa.hernandez044@student.edu',
        'phone_number'  => '555-9331374',
        'address'       => 'Dallas',
        'gpa'           => 3.61,
    ],
    [
        'student_id'    => 'STU045',
        'first_name'    => 'Nancy',
        'last_name'     => 'Thomas',
        'date_of_birth' => '2004-04-08',
        'gender'        => 1,
        'class'         => 'CE101',
        'major'         => 'Marketing',
        'email'         => 'nancy.thomas045@student.edu',
        'phone_number'  => '555-8971800',
        'address'       => 'Chicago',
        'gpa'           => 2.44,
    ],
    [
        'student_id'    => 'STU046',
        'first_name'    => 'Charles',
        'last_name'     => 'Garcia',
        'date_of_birth' => '2004-06-15',
        'gender'        => 1,
        'class'         => 'BA101',
        'major'         => 'Computer Science',
        'email'         => 'charles.garcia046@student.edu',
        'phone_number'  => '555-6573490',
        'address'       => 'Houston',
        'gpa'           => 3.16,
    ],
    [
        'student_id'    => 'STU047',
        'first_name'    => 'Margaret',
        'last_name'     => 'Taylor',
        'date_of_birth' => '2003-07-20',
        'gender'        => 1,
        'class'         => 'EE101',
        'major'         => 'Mechanical Engineering',
        'email'         => 'margaret.taylor047@student.edu',
        'phone_number'  => '555-4688452',
        'address'       => 'Dallas',
        'gpa'           => 3.55,
    ],
    [
        'student_id'    => 'STU048',
        'first_name'    => 'Paul',
        'last_name'     => 'Martin',
        'date_of_birth' => '2003-09-20',
        'gender'        => 2,
        'class'         => 'CE101',
        'major'         => 'English Literature',
        'email'         => 'paul.martin048@student.edu',
        'phone_number'  => '555-3477509',
        'address'       => 'Chicago',
        'gpa'           => 2.21,
    ],
    [
        'student_id'    => 'STU049',
        'first_name'    => 'Mark',
        'last_name'     => 'Martin',
        'date_of_birth' => '2004-09-15',
        'gender'        => 1,
        'class'         => 'ME101',
        'major'         => 'Electrical Engineering',
        'email'         => 'mark.martin049@student.edu',
        'phone_number'  => '555-3635881',
        'address'       => 'Houston',
        'gpa'           => 2.48,
    ],
    [
        'student_id'    => 'STU050',
        'first_name'    => 'James',
        'last_name'     => 'Davis',
        'date_of_birth' => '2005-02-16',
        'gender'        => 2,
        'class'         => 'CS102',
        'major'         => 'Accounting',
        'email'         => 'james.davis050@student.edu',
        'phone_number'  => '555-9396364',
        'address'       => 'Dallas',
        'gpa'           => 2.4,
    ],   
    ];
    public function getList () {
        return $this->list;

    }
}

       